name: Ruff Formatting
on: [push]
jobs:
  run-ruff:
    runs-on: ubuntu-latest
    container: python:3
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: astral-sh/ruff-action@v3.0.1
      - name: Ruff Linting
        run: ruff check
      - name: Ruff Formatting
        run: ruff format --check
